version: '3.8'

#services:
#  mongo:
#    image: mongo:5.0
#    platform: linux/arm64/v8
#    container_name: mongodb
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongodbdata:/data/db
#    restart: always
services:
  mongo:
    image: mongo:5.0
    platform: linux/arm64/v8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    restart: always

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/usmap
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  mongodbdata:
