version: '3.8'

services:
  mongo:
    image: mongo:5.0 
    platform: linux/arm64/v8 
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    restart: always

volumes:
  mongodbdata:
